---
- name: Upgrade OS packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Check if a reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: reboot_required_file

- name: Reboot the server (if required).
  ansible.builtin.reboot:
    reboot_timeout: 900
  when: reboot_required_file.stat.exists == true

- name: Install dependency packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: Clone Neovim configuration from GitHub
  git:
    repo: "https://github.com/neovim/neovim"
    dest: /tmp/neovim

- name: Run make to build Neovim
  community.general.make:
    chdir: /tmp/neovim
    jobs: 4
    params: CMAKE_BUILD_TYPE=RelWithDebInfo
  register: make_result

- name: Run make install
  community.general.make:
    chdir: /tmp/neovim
    target: install
  register: install_result
  when: make_result is not skipped

- name: Clean up source directory
  ansible.builtin.file:
    path: /tmp/neovim
    state: absent
  when: install_result is not skipped
