- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow specific ports through the firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ allowed_ports }}"

- name: Enable UFW and set default rules
  ufw:
    # state: enabled
    state: disabled
    direction: incoming
    policy: deny
