---
- name: Install WireGuard
  apt:
    name: wireguard
    state: present

- name: install resolvconf
  apt:
    name: resolvconf
    state: present

- name: Update wireguard configuration file
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: "0600"

- name: Enable and start WireGuard
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started
