---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Install Nginx Plus module RTMP for RPi
  apt:
    # name: nginx-plus-modue-rtmp
    name: libnginx-mod-rtmp
    state: present

- name: Config files
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "644"

- name: Ensure Nginx is started
  ansible.builtin.service:
    name: nginx
    state: started

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
# - name: Start custom process
#   ansible.builtin.command:
#     cmd: ffmpeg -f v4l2 -i /dev/video0 -c:v libx264 -preset ultrafast -f flv rtmp://<RTMP_SERVER_IP>/live/stream
#     creates: tmp/video_streaming.pid
