- name: Install pyenv on Linux/macOS (Zsh)
  hosts: all
  become: false
  vars:
    pyenv_root: "{{ ansible_env.HOME }}/.pyenv"
    pyenv_version: "v2.5.3" # Change to latest version if needed
  tasks:
    # - name: Install dependencies for pyenv
    #   package:
    #     name:
    #       - make
    #       - build-essential
    #       - libssl-dev
    #       - zlib1g-dev
    #       - libbz2-dev
    #       - libreadline-dev
    #       - libsqlite3-dev
    #       - wget
    #       - curl
    #       - llvm
    #       - libncursesw5-dev
    #       - xz-utils
    #       - tk-dev
    #       - libffi-dev
    #       - liblzma-dev
    #       - git
    #     state: present

    - name: Clone pyenv repository
      git:
        repo: "https://github.com/pyenv/pyenv.git"
        dest: "{{ pyenv_root }}"
        version: "{{ pyenv_version }}"

    - name: Add pyenv to Zsh profile (~/.zshrc)
      blockinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        block: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - pyenv"

    - name: Source .zshrc
      shell: source ~/.zshrc
      args:
        executable: /bin/zsh

    # - name: Verify pyenv installation
    #   command: pyenv --version
    #   register: pyenv_check
    #   changed_when: false

    # - debug:
    #     msg: "Pyenv installed successfully: {{ pyenv_check.stdout }}"
